### ISSUE TITLE
upgrading from v1.77 to v1.89, resulting in crash on PlayGTAIV launch. 

### ISSUE THREAD

**Issue by r3538987** [Zolika1351/GTAIV.EFLC.FusionFix#1]
All I get from logs is just OS event viewer. 
Removing FusionFix ASI files, makes game again launch properly. 

> Faulting application name: GTAIV.exe, version: 1.0.7.0, time stamp: 0x4bd9efbe
> Faulting module name: GTAIV.EFLC.FusionFix.asi, version: 1.2.0.0, time stamp: 0x64f8906c
> Exception code: 0xc0000005
> Fault offset: 0x0000fd88
> Faulting process id: 0x81b4
> Faulting application start time: 0x01d9e0de0d5a7727
> Faulting application path: E:\Games\GTA.4.v1.0.7.0.CE.Downgraded - Experimental\GTAIV.exe
> Faulting module path: E:\Games\GTA.4.v1.0.7.0.CE.Downgraded - Experimental\plugins\GTAIV.EFLC.FusionFix.asi
> Report Id: 851ce995-3915-4ddc-9644-f9c3da49440f
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by Zolika1351** [comment]
Patch 7 support was fixed by 9d5163cc751b8bd9c51845af1273419d64ca660b redownload the latest 1.89 archive and it'll work
