### ISSUE TITLE
v1.89+ makes night pitch dark?

### ISSUE THREAD

**Issue by kazum1kun** [Zolika1351/GTAIV.EFLC.FusionFix#10]
Hello,

I noticed that the graphics are not working after upgrading to v1.89+. Basically towards midnight the game gradually become darker and darker until nothing is visible (other than overlays like mission markers and phones). It appears to be a global filter of some sort.

Please check the following video for a demonstration: https://streamable.com/0b7or4

You can also notice the screen is blurry, which I was able to fix by turning DoF off.

Relevant mod installed:
- 1.0.7.0 downgrade
- FusionFix (PreCE) 1.96
- Various Fixes 1.60
- ZolikaPatch 7.65
- iCEnhancer Natural 3.0
- ZMenuIV 23.09.18.2

After reverting to FusionFix 1.80 (and keeping other mods as-is) the issue went away.

Any idea why is that happening?

**Comment by inhumanesmoke** [comment]
The most likely culprit is iCEnhancer.  You shouldn't be using an ENB with the new shaders in the latest Fusion Fix.  ENBs use their own shaders and Fusion Fix shaders are conflicting with the ENB time cycles.  An ENB also breaks other things in the shaders like volumetric lighting.

**Comment by kazum1kun** [comment]
Ah, good to know. I will get rid of the iCE and see if it still happens.
