### ISSUE TITLE
Compatibility with GTAIV.ShaderFixesCollection?

### ISSUE THREAD

**Issue by r3538987** [Zolika1351/GTAIV.EFLC.FusionFix#2]
Aside from shaders, collection has additional ASI file for v1070/v1080.
Tested version after this commit - https://github.com/Zolika1351/GTAIV.EFLC.FusionFix/commit/9d5163cc751b8bd9c51845af1273419d64ca660b

Game also refuse to start on launch. 
And in Event viewer :
> Faulting application path: E:\Games\GTA.4.v1.0.7.0.CE.Downgraded - Experimental\GTAIV.exe
> Faulting module path: E:\Games\GTA.4.v1.0.7.0.CE.Downgraded - Experimental\plugins\GTAIV.LogDepth.asi

While from brief look game doesn't suffer from z-fighting, but there are still spots where is can be seen. 
Maybe that file is responsible for those rare cases.

**Comment by Zolika1351** [comment]
The logdepth asi is only required if you don't have this mod

**Comment by r3538987** [comment]
Ahh I get it, it's required if using without FF.
I though it's for 1070/80 and should be used always with FF or without.
