### ISSUE TITLE
v1.77 and v1.89, save loading times increased

### ISSUE THREAD

**Issue by r3538987** [Zolika1351/GTAIV.EFLC.FusionFix#4]
As mentioned in discord, will copy that report over here as well. 
SkipIntro = 1
SkipMenu = 1

v1.77 - takes 20 seconds to get into game. (After launching PlayGTAIV)
v1.89 - minute and 12 seconds. 

Same mod amount in update folder (similar behavior with only FF files).

Usually you have floating screens during load, and later quick black screen with Loading Mission Title. 
In latest versions, floating ones go away quickly, and you stuck on black one, for 40-50 seconds.

**Comment by r3538987** [comment]
Additional piece 

v1.77, loads save also slowly, but only when you set FPS limiter - Off.
(limiter 60, loads quickly)
v1.80, with limiter ON (60) or OFF, in both cases - it's slow.

**Comment by Zolika1351** [comment]
Can you check if the newest version of v1.91 that I just pushed fixed it or not?

**Comment by r3538987** [comment]
Unfortunately it's same with v1.91. 
What you think, is it possible to track down long loading resource with process monitor tool?

**Comment by r3538987** [comment]
After bunch of configuration tests, managed to reproduce behavior I mentioned with limiter. 
v1.91
Framerate limiter - Off = loads entire minute
Framerate limiter - 60 = loads super fast, 15-18 seconds and you are in game. 


For me, quick loading config is like this.
>[MAIN]
>SkipIntro = 1
>SkipMenu = 1
>BorderlessWindowed = 1

>[FRAMELIMIT]
>FpsLimitPreset = 7
>FrameLimitType = 2                         // 1: realtime (thread-lock)  |  2: accurate (sleep-yield), uses less resources
>FpsLimit = 0                               // used when FPS Limit menu toggle is set to ON
>CutsceneFpsLimit = 60
>ScriptCutsceneFovLimit = 30

>-adapter 0
>-width 5120 height 2880
>-availablevidmem 3072.0
>-norestrictions
>-nomemrestrict

**Comment by Zolika1351** [comment]
What speed does it load without the mod?

**Comment by r3538987** [comment]
Interesting indeed.
with FusionFix, but skips disabled ~46 seconds. 
without FusionFix, game is slow ~ 1 minute and 50 seconds.

All this points out towards, that other mods may have such effect.

**Comment by Zolika1351** [comment]
It's not a problem with FF then, closing the issue
