### ISSUE TITLE
v1.89 All extra options toggle at once. 

### ISSUE THREAD

**Issue by JRC1999** [Zolika1351/GTAIV.EFLC.FusionFix#5]
I was hoping this was because I accidentally used the main branch version, but alas the problem persists. If you toggle any of the extra graphical or visual options, they all lock together, except motion blur. The Console Gamma and, screen filter, and frame limiter (which doesn't appear but I see it cycle through 30 and 60 on the other two) do the same thing
![20230906151654_1](https://github.com/Zolika1351/GTAIV.EFLC.FusionFix/assets/144276937/522a8d72-3c23-4b75-a2ed-5038d392043d)
![20230906151653_1](https://github.com/Zolika1351/GTAIV.EFLC.FusionFix/assets/144276937/fbf3132f-bc86-42da-a0a5-5c40cfbf6b33)

Somewhat unrelated but I would like to bring back the headlight shadows. Is that possible by disabling the flickering fix? I'd assume not since changing the value from 1 to 0 did nothing.

**Comment by Zolika1351** [comment]
This usually means the mod isn't loading at all, are you sure you didn't leave a duplicate asi somewhere by accident? Keep in mind this mod has the asi in the root dir while the main branch version is in the plugins folder

**Comment by JRC1999** [comment]
![Screenshot (178)](https://github.com/Zolika1351/GTAIV.EFLC.FusionFix/assets/144276937/d392f489-9370-4a90-9cb7-86972a5aec21)

Here is my GTA IV folder. Unless it'd try and load it from the trash folder, there _shouldn't_ be any duplicates. 

EDIT: I _did_ go back to the prior version. But even upon updating it looked the same.

**Comment by Zolika1351** [comment]
The date on your fusionfix asi is from 2 days ago, redownload it and replace the asi with the newest one

**Comment by JRC1999** [comment]
> The date on your fusionfix asi is from 2 days ago, redownload it and replace the asi with the newest one

I had. I forgot when I screenshotted that I'd already gone back to the old version because of the issue. I may delete the old one and the update folder and try again but it didn't work when I tried earlier.

**Comment by JRC1999** [comment]
Deleting all traces of the old version and starting over fixed it. Am also on 1.94 now and everything seems to work just fine.
