### ISSUE TITLE
[ISSUE] Black rain drops on-screen

### ISSUE THREAD

**Issue by valentyn-l** [Zolika1351/GTAIV.EFLC.FusionFix#6]
![](https://cdn.discordapp.com/attachments/1111302633781723280/1149186557098590289/20230907043355_1.jpg)

**Comment by valentyn-l** [comment]
Also missing refraction

**Comment by Zolika1351** [comment]
Are you sure you have the latest version? I released a hotfix for 1.89 a few hours after the initial one to fix this specifically

**Comment by valentyn-l** [comment]
All fixed now with latest version. I hadn't realized you posted a hotfix. Thanks!
