### ISSUE TITLE
Ini config file seems to be outdated in preCE version

### ISSUE THREAD

**Issue by NotEvenFlinched** [Zolika1351/GTAIV.EFLC.FusionFix#7]
I've noticed that there are significant differences in ini config between main version and preCE fork (compared latest 1.94 versions), I highlighted options and text hints that are absent on preCE config on the screenshot
P.S. Also, "ForceDepthOfFieldInCutscenes" is absent in main version, but presented in preCE
![bug](https://github.com/Zolika1351/GTAIV.EFLC.FusionFix/assets/41795843/a910ca46-432c-422a-86c7-2368c79a2823)

**Comment by Zolika1351** [comment]
I forgot to update the ini, fixed
