### ISSUE TITLE
BAWSAQ sign in Star Junction not illuminated

### ISSUE THREAD

**Issue by ghost** [Zolika1351/GTAIV.EFLC.FusionFix#8]
The BAWSAQ sign in Star Junction in front of Burger Shot seems to be broken, as it's not illuminated at all unlike in the before/after screenshot.
![Screenshot (35242)](https://github.com/Zolika1351/GTAIV.EFLC.FusionFix/assets/54059259/f74f5125-805e-4dbc-a83b-d4d4d3fc4a20)

What it should be:
![TfvY8eU](https://github.com/Zolika1351/GTAIV.EFLC.FusionFix/assets/54059259/46834f33-987e-4afe-ac76-cba2893a2a1b)

The rest of the emissive shaders are rendered correctly, though.
![Screenshot (35243)](https://github.com/Zolika1351/GTAIV.EFLC.FusionFix/assets/54059259/e2b9399f-c4c0-4d7d-8dde-01f94b8dbbd0)
![Screenshot (35244)](https://github.com/Zolika1351/GTAIV.EFLC.FusionFix/assets/54059259/634756c5-ab6c-4cac-9bdc-a5a8c4e68aa0)

**Comment by Meesmoth** [comment]
What it should be:
https://imgur.com/TfvY8eU

**Comment by Zolika1351** [comment]
This seems to be an issue in all versions, can't do anything about it until it's fixed by the main team

**Comment by Parallellines0451** [comment]
It's not broken, that's how it's supposed to look, and that's how it looks on consoles as well.

**Comment by Zolika1351** [comment]
Alright, in that case I'm closing the issue
